### ISSUE TITLE
error when using generate and upscale option "sd_checkpoint_hash"

### ISSUE THREAD

**Issue by Kking1111** [AIrjen/OneButtonPrompt#107]
Traceback (most recent call last):
  File "C:\stable-diffusion-webui\venv\lib\site-packages\gradio\routes.py", line 422, in run_predict
    output = await app.get_blocks().process_api(
  File "C:\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 1323, in process_api
    result = await self.call_function(
  File "C:\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 1051, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "C:\stable-diffusion-webui\venv\lib\site-packages\anyio\to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "C:\stable-diffusion-webui\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "C:\stable-diffusion-webui\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "C:\stable-diffusion-webui\extensions\OneButtonPrompt\main.py", line 52, in generateimages
    currentlyselectedmodelhash = optionsresponsejson["sd_checkpoint_hash"]
KeyError: 'sd_checkpoint_hash'

**Comment by AIrjen** [comment]
Hi! On which version of A1111 are you running?

**Comment by Kking1111** [comment]
It says Version: v1.5.1. May be i enabled the origin/dev also for SDXL.

**Comment by AIrjen** [comment]
Thanks. This option has been introduced in v1.5 onwards. I will look at this soon.

**Comment by AIrjen** [comment]
I did some checks, and I found this: https://github.com/AUTOMATIC1111/stable-diffusion-webui/issues/12185

However, I checked the fix, and it is rolled out in the dev branch as well.

Just some questions:
- Did it work before? If so, what changed that it now isn't working?
- Did you start with --api in the command line of webui?
- Does this happen during processing multiple images, or is this immidate the first error message you get?

**Comment by Kking1111** [comment]
Strangely it has started working, I didn't even update Auto111 and i no longer have origin/dev message coming on when starting Auto1111. But now, when i use "don't generate, only upscale", I get this error:
Found and upscaling files

Traceback (most recent call last):
  File "C:\stable-diffusion-webui\venv\lib\site-packages\gradio\routes.py", line 422, in run_predict
    output = await app.get_blocks().process_api(
  File "C:\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 1323, in process_api
    result = await self.call_function(
  File "C:\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 1051, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "C:\stable-diffusion-webui\venv\lib\site-packages\anyio\to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "C:\stable-diffusion-webui\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "C:\stable-diffusion-webui\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "C:\stable-diffusion-webui\extensions\OneButtonPrompt\main.py", line 302, in generateimages
    if(continuewithnextpart == True):
UnboundLocalError: local variable 'continuewithnextpart' referenced before assignment

**Comment by AIrjen** [comment]
Hi! Thanks for getting back on this. Glad to see its working.

I just got the same issue reported. This was a bug and a mistake by me from one of the latest changes.

Should be fixed now! Sorry, didn't test this when I made the latest batch of large changes.
