### ISSUE TITLE
Error when using Start generating but only upscale in One Button Run and Upscale.

### ISSUE THREAD

**Issue by Systemac** [AIrjen/OneButtonPrompt#111]
Hello, 

First, thank's so much for you work !!

however I have a problem with One button run and upscale (am on A1111) i wan't to only upscale but the script encounters this error:

Traceback (most recent call last):
  File "E:\Dev\stable-diffusion-webui\venv\lib\site-packages\gradio\routes.py", line 422, in run_predict
    output = await app.get_blocks().process_api(
  File "E:\Dev\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 1323, in process_api
    result = await self.call_function(
  File "E:\Dev\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 1051, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "E:\Dev\stable-diffusion-webui\venv\lib\site-packages\anyio\to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "E:\Dev\stable-diffusion-webui\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "E:\Dev\stable-diffusion-webui\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "E:\Dev\stable-diffusion-webui\extensions\OneButtonPrompt\main.py", line 227, in generateimages
    if(img2imgactivate == False or continuewithnextpart == False):  # If we dont want to run, turn it off
UnboundLocalError: local variable 'continuewithnextpart' referenced before assignment

**Comment by AIrjen** [comment]
That is most definitely a bug created by me! Will try and get this sorted soon.

**Comment by Systemac** [comment]
Thank's so much :)

**Comment by AIrjen** [comment]
Should be fixed now! Sorry, didn't test this when I made the latest batch of large changes.
