### ISSUE TITLE
UnicodeEncodeError: 'gbk' codec can't encode character '\U0001f916' in position 141: illegal multibyte sequence

### ISSUE THREAD

**Issue by whmc76** [AIrjen/OneButtonPrompt#119]
!!! Exception during processing !!!
Traceback (most recent call last):
  File "E:\ComfyUI_windows_portable\ComfyUI\execution.py", line 151, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
  File "E:\ComfyUI_windows_portable\ComfyUI\execution.py", line 81, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
  File "E:\ComfyUI_windows_portable\ComfyUI\execution.py", line 74, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
  File "E:\ComfyUI_windows_portable\ComfyUI\custom_nodes\OneButtonPrompt\OneButtonPromptNodes.py", line 74, in Comfy_OBP
    generatedprompt = build_dynamic_prompt(insanitylevel,subject,artist,imagetype,False,"","","",1,"",custom_subject,True,"",imagemodechance, humanoids_gender, subject_subtype_objects, subject_subtypes_humanoids, subject_subtypes_concepts, False)
  File "E:\ComfyUI_windows_portable\ComfyUI\custom_nodes\onebuttonprompt\build_dynamic_prompt.py", line 1951, in build_dynamic_prompt
    print(completeprompt)
  File "E:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Manager\prestartup_script.py", line 24, in write
    self.file.write(message)
UnicodeEncodeError: 'gbk' codec can't encode character '\U0001f916' in position 141: illegal multibyte sequence

Prompt executed in 0.42 seconds
adding something rare to the pro

**Comment by AIrjen** [comment]
Hi, yes, will look at this soon. There are some nodes in ComfyUI which cannot handle emoji's (in this case: 🤖)

I will try and make emoji's optional via the interface.

In the meantime, you can turn emoji generation off by creating an empty emojis_replace.csv file in the \userfiles\ folder:
https://github.com/AIrjen/OneButtonPrompt/blob/main/user_guides/custom_files.md

**Comment by whmc76** [comment]
lol, thanks, i will try

**Comment by AIrjen** [comment]
Was able to adjust for this.

In the latest release, in ComfyUI, it now has a emoji (True/False) option. It now defaults to False, meaning it will not generate them until turning this on.
