### ISSUE TITLE
button run and upscale doesn't work anymore

### ISSUE THREAD

**Issue by vallagurd** [AIrjen/OneButtonPrompt#138]
hi 
when i try to use the one button run and upscale i got this error everytime
and i reinstalled SD automatik 1111 clean but same error
Traceback (most recent call last):
  File "C:\stable_diff\sd.webui\system\python\lib\site-packages\gradio\routes.py", line 488, in run_predict
    output = await app.get_blocks().process_api(
  File "C:\stable_diff\sd.webui\system\python\lib\site-packages\gradio\blocks.py", line 1431, in process_api
    result = await self.call_function(
  File "C:\stable_diff\sd.webui\system\python\lib\site-packages\gradio\blocks.py", line 1103, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "C:\stable_diff\sd.webui\system\python\lib\site-packages\anyio\to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "C:\stable_diff\sd.webui\system\python\lib\site-packages\anyio\_backends\_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "C:\stable_diff\sd.webui\system\python\lib\site-packages\anyio\_backends\_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "C:\stable_diff\sd.webui\system\python\lib\site-packages\gradio\utils.py", line 707, in wrapper
    response = f(*args, **kwargs)
  File "C:\stable_diff\sd.webui\webui\extensions\OneButtonPrompt\main.py", line 54, in generateimages
    currentlyselectedmodelhash = optionsresponsejson["sd_checkpoint_hash"]
KeyError: 'sd_checkpoint_hash'

thanks for the feedback ^^

**Comment by AIrjen** [comment]
Hi! This error can occur when A1111 is started without the --api option. One Button Prompt and upscale works with API calls to A1111.

You need to set the following in your webui-user.bat file:

`set COMMANDLINE_ARGS=--api`

Does that help?

**Comment by vallagurd** [comment]
hi ^^
yeah thx a lot, it works!

**Comment by AIrjen** [comment]
Yeahhh, hope you enjoy this extension! :)

**Comment by vallagurd** [comment]
yeah it really rocks!!!
