### ISSUE TITLE
Dev build of A1111 breaks OneButtonPrompt

### ISSUE THREAD

**Issue by Diamond-Shark-art** [AIrjen/OneButtonPrompt#154]
Hi, first of all, happy new year! And thanks for this amazing plugin! 

Just as a heads up, the latest dev build of A1111 breaks it. Looks like things added these past days wil ship in 1.7.0

This is the code from the error:

*** Error loading script: api.py
    Traceback (most recent call last):
      File "C:\Users\Gebruiker\stable-diffusion-webui\modules\scripts.py", line 515, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "C:\Users\Gebruiker\stable-diffusion-webui\modules\script_loading.py", line 10, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "C:\Users\Gebruiker\stable-diffusion-webui\extensions\OneButtonPrompt\scripts\api.py", line 4, in <module>
        from scripts.onebuttonprompt import subjects, artists, imagetypes
      File "C:\Users\Gebruiker\stable-diffusion-webui\extensions\OneButtonPrompt\scripts\onebuttonprompt.py", line 43, in <module>
        upscalerlist = get_upscalers()
      File "C:\Users\Gebruiker\stable-diffusion-webui\extensions\OneButtonPrompt\model_lists.py", line 18, in get_upscalers
        upscalerlistfromwWebUI = upscalers_on_startup()
      File "C:\Users\Gebruiker\stable-diffusion-webui\extensions\OneButtonPrompt\model_lists.py", line 89, in upscalers_on_startup
        modelloader.cleanup_models()
    AttributeError: module 'modules.modelloader' has no attribute 'cleanup_models'

---
*** Error loading script: onebuttonprompt.py
    Traceback (most recent call last):
      File "C:\Users\Gebruiker\stable-diffusion-webui\modules\scripts.py", line 515, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "C:\Users\Gebruiker\stable-diffusion-webui\modules\script_loading.py", line 10, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "C:\Users\Gebruiker\stable-diffusion-webui\extensions\OneButtonPrompt\scripts\onebuttonprompt.py", line 43, in <module>
        upscalerlist = get_upscalers()
      File "C:\Users\Gebruiker\stable-diffusion-webui\extensions\OneButtonPrompt\model_lists.py", line 18, in get_upscalers
        upscalerlistfromwWebUI = upscalers_on_startup()
      File "C:\Users\Gebruiker\stable-diffusion-webui\extensions\OneButtonPrompt\model_lists.py", line 89, in upscalers_on_startup
        modelloader.cleanup_models()
    AttributeError: module 'modules.modelloader' has no attribute 'cleanup_models'

Hope this helps. Thanks.

**Comment by AIrjen** [comment]
Ohhh thank you for reporting! I’ll have a look this weekend to try and solve this.

happy new year and happy prompting 😊

**Comment by AIrjen** [comment]
Got a little time and made a fix :) It should be fixed on the latest version now.

Thanks for the pro-active alert, it is very much appriciated!

**Comment by Diamond-Shark-art** [comment]
That was fast, thank you :)!
