### ISSUE TITLE
!!! Exception during processing!!! 'int' object has no attribute 'lower'

### ISSUE THREAD

**Issue by buzhiqianshan** [AIrjen/OneButtonPrompt#207]
!!! Exception during processing!!! 'int' object has no attribute 'lower'
Traceback (most recent call last):
  File "F:\ComfyUI\execution.py", line 151, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
  File "F:\ComfyUI\execution.py", line 81, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
  File "F:\ComfyUI\execution.py", line 74, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
  File "F:\ComfyUI\custom_nodes\OneButtonPrompt\OneButtonPromptNodes.py", line 637, in Comfy_OBP_OneButtonPreset
    generatedprompt = build_dynamic_prompt(insanitylevel=insanitylevel,
  File "F:\ComfyUI\custom_nodes\OneButtonPrompt\build_dynamic_prompt.py", line 28, in build_dynamic_prompt
    prompt_enhancer = prompt_enhancer.lower()
AttributeError: 'int' object has no attribute 'lower'

**Comment by AIrjen** [comment]
Hi! Some of the fields have changed, if you updated without changing anything, they might be in the wrong order. Its a ComfyUI thing, it doesn't understand when new fields are added or removed in the node in the workflow.

They need to look something like this:

![image](https://github.com/AIrjen/OneButtonPrompt/assets/130234949/ad006698-501d-423a-9654-c65691b4c2f7)
