### ISSUE TITLE
IndexError: pop from empty list

### ISSUE THREAD

**Issue by Jonseed** [AIrjen/OneButtonPrompt#230]
Ran OBP last night, and it ran ok for a while, but eventually failed on replacement = materialreplacementlist.pop() on line 3454 of build_dynamic_prompt.py.

```
!!! Exception during processing !!! pop from empty list
Traceback (most recent call last):
  File "D:\repos\ComfyUI\execution.py", line 323, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\repos\ComfyUI\execution.py", line 198, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\repos\ComfyUI\execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)
  File "D:\repos\ComfyUI\execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\repos\ComfyUI\custom_nodes\OneButtonPrompt\OneButtonPromptNodes.py", line 381, in Comfy_OBP
    generatedpromptlist = build_dynamic_prompt(insanitylevel,subject,artist,imagetype,False,"",prompt_prefix,prompt_suffix,1,"",custom_subject,True,"",imagemodechance, humanoids_gender,"all", "all", "all", False, emojis, seed, custom_outfit, True, base_model, "", prompt_enhancer)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\repos\ComfyUI\custom_nodes\OneButtonPrompt\build_dynamic_prompt.py", line 3454, in build_dynamic_prompt
    replacement = materialreplacementlist.pop()
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
IndexError: pop from empty list
```

Does it need an additional check, like this?
```
if materialreplacementlist:
    replacement = materialreplacementlist.pop()
else:
    # Handle the case where the list is empty
    replacement = None
```

**Comment by AIrjen** [comment]
Sure, fixed!
